# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TypingUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDesktopWidget, QMainWindow
from PyQt5.QtCore import Qt

class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):

        

        screem_size = QDesktopWidget().availableGeometry()
        MainWindow.setObjectName("MainWindow")
        MainWindow.setGeometry(screem_size)

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1319, 888)
        MainWindow.setMinimumSize(QtCore.QSize(1224, 759))
        
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("#lan_combo{\n"
"    color: white;\n"
"    border: none;\n"

"\n"
"}\n"
"\n"
"#lan_combo::drop-down {\n"
"    border: 0px;\n"
"    color: white;\n"
"}\n"
"\n"
"\n"
"#lan_combo::down-arrow {\n"
"    image: url(:/Icons/Recources/Polygon3.png);\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"#lan_combo QListView{\n"
"    padding: 20px;\n"
"    color: white;\n"
"}")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgba(38, 69, 110, 1)")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        # self.verticalLayout_5.SetFixedSize(500, 300)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 108))
        self.widget.setObjectName("widget")
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setGeometry(QtCore.QRect(36, 23, 633, 87))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(83, 83))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Recources/keyboard-svgrepo-com 1.png"))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(211, 16777215))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Recources/FastTyper.png"))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lan_combo = QtWidgets.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(11)
        self.lan_combo.setFont(font)
        self.lan_combo.setStyleSheet("#lan_combo{\n"
"    color: white;\n"
"    border: none;\n"
"\n"
"}\n"
"\n"
"#lan_combo::drop-down {\n"
"    border: 0px;\n"
"}\n"
"\n"
"\n"
"#lan_combo::down-arrow {\n"
"    image: url(:/Icons/Recources/Polygon3.png);\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"#lan_combo QListView{\n"
"    padding: 20px;\n"
"}")
        self.lan_combo.setObjectName("lan_combo")
        self.lan_combo.addItem("")
        self.lan_combo.addItem("")
        self.lan_combo.addItem("")
        self.horizontalLayout_3.addWidget(self.lan_combo)
        self.lan_combo_2 = QtWidgets.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(11)
        self.lan_combo_2.setFont(font)
        self.lan_combo_2.setStyleSheet("#lan_combo_2{\n"
"    color: white;\n"
"    border: none;\n"
"\n"
"}\n"
"\n"
"#lan_combo_2::drop-down {\n"
"    border: 0px;\n"
"}\n"
"\n"
"\n"
"#lan_combo_2::down-arrow {\n"
"    image: url(:/Icons/Recources/Polygon3.png);\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"#lan_combo_2 QListView{\n"
"    padding: 20px;\n"
"}")
        self.lan_combo_2.setObjectName("lan_combo_2")
        self.lan_combo_2.addItem("")
        self.lan_combo_2.addItem("")
        self.lan_combo_2.addItem("")
        self.lan_combo_2.addItem("")
        self.horizontalLayout_3.addWidget(self.lan_combo_2)
        self.lan_combo_3 = QtWidgets.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(11)
        self.lan_combo_3.setFont(font)
        self.lan_combo_3.setStyleSheet("#lan_combo_3{\n"
"    color: white;\n"
"    border: none;\n"
"\n"
"}\n"
"\n"
"#lan_combo_3::drop-down {\n"
"    border: 0px;\n"
"}\n"
"\n"
"\n"
"#lan_combo_3::down-arrow {\n"
"    image: url(:/Icons/Recources/Polygon3.png);\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"#lan_combo_3 QListView{\n"
"    padding: 20px;\n"
"}")
        self.lan_combo_3.setObjectName("lan_combo_3")
        self.lan_combo_3.addItem("")
        self.lan_combo_3.addItem("")
        self.lan_combo_3.addItem("")
        self.horizontalLayout_3.addWidget(self.lan_combo_3)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.setStretch(0, 1)
        self.verticalLayout_5.addWidget(self.widget)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(50, 50, 50, 50)
        self.gridLayout.setHorizontalSpacing(50)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget2 = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget2.sizePolicy().hasHeightForWidth())
        self.widget2.setSizePolicy(sizePolicy)
        self.widget2.setMaximumSize(QtCore.QSize(16777215, 92))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.time_label = QtWidgets.QLabel(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_label.sizePolicy().hasHeightForWidth())
        self.time_label.setSizePolicy(sizePolicy)
        self.time_label.setMaximumSize(QtCore.QSize(80, 77))
        self.time_label.setSizeIncrement(QtCore.QSize(1, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(16)
        self.time_label.setFont(font)
        self.time_label.setStyleSheet("color: white;")
        self.time_label.setObjectName("time_label")
        self.verticalLayout_2.addWidget(self.time_label)
        self.time = QtWidgets.QLabel(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time.sizePolicy().hasHeightForWidth())
        self.time.setSizePolicy(sizePolicy)
        self.time.setMaximumSize(QtCore.QSize(120, 77))
        self.time.setSizeIncrement(QtCore.QSize(1, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(24)
        self.time.setFont(font)
        self.time.setStyleSheet("color: white;")
        self.time.setObjectName("time")
        self.verticalLayout_2.addWidget(self.time)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.wpm_acc_label = QtWidgets.QLabel(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wpm_acc_label.sizePolicy().hasHeightForWidth())
        self.wpm_acc_label.setSizePolicy(sizePolicy)
        self.wpm_acc_label.setMaximumSize(QtCore.QSize(192, 77))
        self.wpm_acc_label.setSizeIncrement(QtCore.QSize(1, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(16)
        self.wpm_acc_label.setFont(font)
        self.wpm_acc_label.setStyleSheet("color: white;")
        self.wpm_acc_label.setObjectName("wpm_acc_label")
        self.verticalLayout_3.addWidget(self.wpm_acc_label)
        self.wpm_acc = QtWidgets.QLabel(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wpm_acc.sizePolicy().hasHeightForWidth())
        self.wpm_acc.setSizePolicy(sizePolicy)
        self.wpm_acc.setMaximumSize(QtCore.QSize(168, 77))
        self.wpm_acc.setSizeIncrement(QtCore.QSize(1, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(24)
        self.wpm_acc.setFont(font)
        self.wpm_acc.setStyleSheet("color: white;")
        self.wpm_acc.setObjectName("wpm_acc")
        self.verticalLayout_3.addWidget(self.wpm_acc)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addWidget(self.widget2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.display_box = QtWidgets.QLabel(self.frame)
        self.display_box.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.display_box.setFont(font)
        self.display_box.setStyleSheet('color: white;\n'"border: 4px solid black;\n"
            "border-radius: 28px;\n"
            "background-color: rgba(34, 61, 97, 1);\n"
            "margin-bottom: 40px; padding: 5px;\n"
            "font-family: 'Roboto Mono';\n"
            "font-size : 50px\n")
        self.display_box.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.display_box.setWordWrap(True)
        # self.display_box_box.setFixedSize()
        self.display_box.setObjectName("display_box")
        self.verticalLayout.addWidget(self.display_box)
        spacerItem2 = QtWidgets.QSpacerItem(20, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.input_box = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_box.sizePolicy().hasHeightForWidth())
        self.input_box.setSizePolicy(sizePolicy)
        self.input_box.setMinimumSize(QtCore.QSize(1, 21))
        self.input_box.setMaximumSize(QtCore.QSize(16777215, 90))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(18)
        self.input_box.setFont(font)
        self.input_box.setStyleSheet("border: 4px solid black;\n"
"color: white;\n"
"border-radius: 28px;\n"
"padding-left: 10px;\n"
"background-color: rgba(34, 61, 97, 1);")
        self.input_box.setText("")
        self.input_box.setCursorPosition(0)
        self.input_box.setObjectName("input_box")
        self.verticalLayout.addWidget(self.input_box)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.frame)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lan_combo.setItemText(0, _translate("MainWindow", "English   "))
        self.lan_combo.setItemText(1, _translate("MainWindow", "Tetun   "))
        self.lan_combo.setItemText(2, _translate("MainWindow", "Indonesian    "))
        self.lan_combo_2.setItemText(0, _translate("MainWindow", "15      "))
        self.lan_combo_2.setItemText(1, _translate("MainWindow", "30      "))
        self.lan_combo_2.setItemText(2, _translate("MainWindow", "60      "))
        self.lan_combo_2.setItemText(3, _translate("MainWindow", "90      "))
        self.lan_combo_3.setItemText(0, _translate("MainWindow", "Easy  "))
        self.lan_combo_3.setItemText(1, _translate("MainWindow", "Medium"))
        self.lan_combo_3.setItemText(2, _translate("MainWindow", "Hard  "))
        self.time_label.setText(_translate("MainWindow", "Time:"))
        self.time.setText(_translate("MainWindow", "00"))
        self.wpm_acc_label.setText(_translate("MainWindow", "WPM/ACCURACY"))
        self.wpm_acc.setText(_translate("MainWindow", "00/0%"))
        self.display_box.setText(_translate("MainWindow", "Press any Letter"))
        self.input_box.setPlaceholderText(_translate("MainWindow", "Type Here"))

    
import recources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
